[package]
name = "poc-function"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_utils = { git = "https://github.com/sub07/rust-utils" }
paste = "1.0"
